services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gim_dev
      - POSTGRES_USER=pato
      - POSTGRES_PASSWORD=pato_pass
    restart: always

  web:
    build: .
    # En local usamos runserver para tener auto-reload
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
    depends_on:
      - web

# CRÍTICO: Declaración global de volúmenes
volumes:
  postgres_data: