# Generated by Django 5.1.15 on 2026-05-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('fuerza', 'Fuerza'), ('cardio', 'Cardio'), ('flexibilidad', 'Flexibilidad')], default='fuerza', max_length=50)),
                ('descripcion_tecnica', models.TextField(help_text='Consejo para la técnica correcta')),
                ('imagen_gif', models.URLField(blank=True, help_text='URL del GIF o imagen ilustrativa')),
                ('musculos_trabajados', models.CharField(help_text='Ej: Pecho, Tríceps', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioEnRutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.PositiveIntegerField(default=3)),
                ('repeticiones', models.PositiveIntegerField(default=12)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='workouts.rutina')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.rutina')),
            ],
        ),
    ]
