# Generated by Django 5.1.15 on 2026-05-15 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesionentrenamiento',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='descripcion_tecnica',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='imagen_gif',
        ),
        migrations.RemoveField(
            model_name='ejercicio',
            name='musculos_trabajados',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='musculos_principales',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tecnica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='tipo',
            field=models.CharField(choices=[('FUERZA', 'Fuerza (Reps/Peso)'), ('CARDIO', 'Cardio (Tiempo/Distancia)')], default='FUERZA', max_length=10),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link a GIF o Video de YouTube'),
        ),
        migrations.AddField(
            model_name='ejercicioenrutina',
            name='descanso_segundos',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='altura_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rutina',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rutina',
            name='ejercicios',
            field=models.ManyToManyField(through='workouts.EjercicioEnRutina', to='workouts.ejercicio'),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesionentrenamiento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ejercicioenrutina',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ejercicioenrutina',
            name='repeticiones',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='ejercicioenrutina',
            name='rutina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.rutina'),
        ),
        migrations.AlterField(
            model_name='ejercicioenrutina',
            name='series',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='LogEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('series_completadas', models.IntegerField()),
                ('repeticiones_reales', models.IntegerField(blank=True, null=True)),
                ('peso_utilizado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_segundos', models.IntegerField(blank=True, null=True)),
                ('calorias_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
