# Generated by Django 5.2.14 on 2026-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_rename_fecha_sesionentrenamiento_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logejercicio',
            name='tiempo_segundos',
        ),
        migrations.AddField(
            model_name='ejercicioenrutina',
            name='peso_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='logejercicio',
            name='tiempo_descanso_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logejercicio',
            name='tiempo_esfuerzo_segundos',
            field=models.IntegerField(default=0),
        ),
    ]
