# Generated by Django 5.2.14 on 2026-05-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_logejercicio_tiempo_segundos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutina',
            name='es_publica',
            field=models.BooleanField(default=False),
        ),
    ]
